version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running tests...
      - npm test   # Make sure you have a test script in package.json

  build:
    commands:
      - echo Building the project...
      - npm run build

  post_build:
    commands:
      - echo Build and tests completed successfully.

artifacts:
  files:
    - '**/*'
    - '!**/node_modules/**'

cache:
  paths:
    - 'node_modules/**/*'

