version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the project...
      - npm run build
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync build/ s3://your-bucket-name --delete
artifacts:
  files:
    - '**/*'
  base-directory: build

